version: '3.1'

services:
    db:
        image: postgres:12
        container_name: db_drupal
        restart: always
        volumes:
            - ./sql:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_DB: "${DB}"
            POSTGRES_USER: "${DBU}"
    adminer:
        image: adminer
        restart: always
        ports:
            - "8001:8080"
    drupal:
        image: drupal:9-php7.4-apache
        container_name: drupal_interface
        restart: always
        ports:
            - "8000:80"
        working_dir: /opt
        volumes:
            - .:/opt:z
        environment:
            HOST: "${DBH}"
            DBASE: "${DB}"
            USER: "${DBU}"
            PASS: "${DBP}"
        command: bash -c "composer update && rm /var/www/html && ln -s /opt/web /var/www/html && /usr/local/bin/apache2-foreground"
